routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/login/phone', [\App\Http\Controllers\Auth\LoginController::class,'phone'])->name('login.phone');
Route::post('/login/phone', [\App\Http\Controllers\Auth\LoginController::class,'verify']);

Route::get('/verify/{token}', [\App\Http\Controllers\Auth\RegisterController::class, 'verify'])->name('register.verify');


Route::get('/cabinet', [\App\Http\Controllers\Cabinet\HomeController::class,'index'])->name('cabinet.home');

// Cabinet of User
Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'namespace' => 'App\Http\Controllers\Cabinet',
        'middleware' => ['auth'],
    ],
    function(){
        Route::get('/',[\App\Http\Controllers\Cabinet\HomeController::class,'index'])->name('home');
        Route::group(['prefix' => 'profile','as'=>'profile.'],function (){
            Route::get('/',[\App\Http\Controllers\Cabinet\ProfileController::class,'index'])->name('home');
            Route::get('/edit',[\App\Http\Controllers\Cabinet\ProfileController::class,'edit'])->name('edit');
            Route::put('/update',[\App\Http\Controllers\Cabinet\ProfileController::class,'update'])->name('update');
            Route::get('/phone',[\App\Http\Controllers\Cabinet\PhoneController::class,'form'])->name('phone');
            Route::post('/phone',[\App\Http\Controllers\Cabinet\PhoneController::class,'request']);
            Route::put('/phone',[\App\Http\Controllers\Cabinet\PhoneController::class,'verify'])->name('phone.verify');

            Route::post('/phone/auth', [\App\Http\Controllers\Cabinet\PhoneController::class,'auth'])->name('phone.auth');
        });
        Route::resource('adverts',"Adverts\AdvertController");

    }
);
/** Adminka */
Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'namespace' => 'App\Http\Controllers\Admin',
        'middleware' => ['auth','can:admin-panel']
    ],
    function (){
        Route::get('/',[\App\Http\Controllers\Admin\HomeController::class,'index'])->name('home');
        Route::post('/users/{user}/verify',[\App\Http\Controllers\Admin\UsersController::class,'verify'])->name('users.verify');
        Route::resource('users','UsersController');
        Route::resource('regions','RegionsController');
/** Adverts (Adminka E`lonlar) */
        Route::group(
            [
                'prefix' => 'adverts',
                'as' => 'adverts.',
                'namespace' => 'Adverts',
//                'middleware' => ['auth']
            ],
            function (){
                Route::resource('categories','CategoryController');

                Route::group(['prefix' => 'categories/{category}','as'=>'categories.'], function(){
                    Route::post('/first','CategoryController@first')->name('first');
                    Route::post('/up','CategoryController@up')->name('up');
                    Route::post('/down','CategoryController@down')->name('down');
                    Route::post('/last','CategoryController@last')->name('last');

                    Route::resource('attributes','AttributeController')->except('index');
                });

            }
        );
    }
);

app/Http/Controllers/Admin/RegionsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entity\Region;
use App\Entity\User\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Users\CreateRequest;
use App\Http\Requests\Admin\Users\UpdateRequest;
use App\UseCases\Auth\RegisterService;
use DaveJamesMiller\Breadcrumbs\Facades\Breadcrumbs;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class RegionsController extends Controller
{

    public function index()
    {
        $regions = Region::whereNull("parent_id")->orderBy('id','desc')->paginate(20);
        return view('admin.regions.index',compact('regions'));
    }

    public function create(Request $request)
    {
        $region = null;
        if ($request->get('id')) {
            $region = Region::findOrFail($request['id']);
        }
        return view('admin.regions.create',compact('region'));
    }

    public function store(Request $request, Region $region)
    {
        $this->validate($request,[
            'name'=>'required|string|max:255|unique:regions,name,NULL,id,parent_id,'.($request['region_id'] ?: 'NULL'),
            'slug'=>'required|string|max:255|unique:regions,slug,NULL,id,parent_id,'.($request['region_id'] ?: 'NULL'),
            'parent_id'=>'nullable|exists:regions,id',
        ]);
        $region = Region::create($request->only(['name','slug','parent_id']));
        return redirect()->route('admin.regions.show',compact('region'));
    }

    public function show(Region $region)
    {
        $regions = Region::whereParentId($region->id)->orderBy('name')->paginate(20);
        return view('admin.regions.show',compact('region','regions'));
    }

    public function edit(Region $region)
    {
        return view('admin.regions.edit',compact('region'));
    }


    public function update(Request $request, Region $region)
    {
        $this->validate($request,[
            'name'=>'required|string|max:255|unique:regions,name,'.$region->id.',id,parent_id,'.$region->parent_id,
            'slug'=>'required|string|max:255|unique:regions,slug,'.$region->id.',id,parent_id,'.$region->parent_id,
        ]);
        $region->update($request->only('name','slug'));
        return redirect()->route('admin.regions.show',compact('region'));
    }

    public function destroy(Region $region)
    {
        $region->delete();
        return redirect()->route('admin.regions.index');
    }

}

resources/views/admin/regions/_list.blade.php
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Slug</th>
        <th>Parent</th>
    </tr>
    </thead>
    <tbody>

    @foreach ($regions as $region)
        <tr>
            <td>{{ $region->id }}</td>
            <td><a href="{{ route('admin.regions.show', $region) }}">{{ $region->name }}</a></td>
            <td>{{ $region->slug }}</td>
            <td>{{ $region->parent ?  $region->parent->name : ''}}</td>
        </tr>
    @endforeach

    </tbody>
</table>

resources/views/admin/regions/_nav.blade.php
<ul class="nav nav-tabs mb-3">
    <li class="nav-item"><a class="nav-link" href="{{route('admin.home')}}">Dashboard</a></li>
    <li class="nav-item"><a class="nav-link active" href="{{route('admin.regions.index')}}">Regions</a></li>
    <li class="nav-item"><a class="nav-link" href="{{route('admin.users.index')}}">Users</a></li>
    <li class="nav-item"><a class="nav-link" href="{{route('admin.adverts.categories.index')}}">Categories</a></li>
</ul>

resources/views/admin/regions/create.blade.php
@extends('layouts.app')
@section('breadcrumbs', Breadcrumbs::render('admin.regions.create',$region))
@section('content')

@include('admin.regions._nav')

    <form method="POST" action="{{ route('admin.regions.store',['region_id'=>$region->id ?? null]) }}">
        @csrf

        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="slug" class="col-form-label">Slug</label>
            <input id="slug" type="text" class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}" name="slug" value="{{ old('slug') }}" required>
            @if ($errors->has('slug'))
                <span class="invalid-feedback"><strong>{{ $errors->first('slug') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/regions/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.regions._nav')

    <form method="POST" action="{{ route('admin.regions.update', $region) }}">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $region->name) }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="slug" class="col-form-label">Slug</label>
            <input id="slug" type="slug" class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}" name="slug" value="{{ old('slug', $region->slug) }}" required>
            @if ($errors->has('slug'))
                <span class="invalid-feedback"><strong>{{ $errors->first('slug') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/regions/index.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.regions._nav')

    <p><a href="{{ route('admin.regions.create',['parent'=>null]) }}" class="btn btn-success">Add Region</a></p>
    @include('admin.regions._list')
    {{ $regions->links() }}
@endsection

resources/views/admin/regions/show.blade.php
@extends('layouts.app')
@section('content')
    @include('admin.regions._nav')

    <div class="d-flex flex-row mb-3">
        <a href="{{ route('admin.regions.edit', $region) }}" class="btn btn-primary mr-1">Edit</a>
        <form method="POST" action="{{ route('admin.regions.destroy', $region) }}" class="mr-1">
            @csrf
            @method('DELETE')
            @can('regions-manage')
            <button class="btn btn-danger">Delete</button>
            @endcan
        </form>
    </div>

    <table class="table table-bordered table-striped">
        <tbody>
        <tr>
            <th>ID</th><td>{{ $region->id }}</td>
        </tr>
        <tr>
            <th>Name</th><td>{{ $region->name }}</td>
        </tr>
        <tr>
            <th>Email</th><td>{{ $region->slug }}</td>
        </tr>
        </tbody>
    </table>
    <p><a href="{{ route('admin.regions.create', ['id'=>$region->id]) }}" class="btn btn-success">Add SubRegion</a></p>

    @include('admin.regions._list')

    {{ $regions->links() }}
@endsection